### ISSUE TITLE
The target predict label gradually becomes unkonwn class after 100 global steps

### ISSUE THREAD

**Issue by WangBowen7** [changwxx/UniOT-for-UniDA#2]

**Comment by changwxx** [comment]
Can you give a more detailed description of the problem you encountered? (e.g. which dataset did you choose? Which transfer task did you set? Did you fully follow our hyperameters setting?)

**Comment by WangBowen7** [comment]
[](url)> Can you give a more detailed description of the problem you encountered? (e.g. which dataset did you choose? Which transfer task did you set? Did you fully follow our hyperameters setting?)

in visda ,I fully follow your hyperameters.The h-score become 0 after 100 global steps and cls_common_acc becomes 0,cls_tp_acc becomes 1.
![捕获](https://user-images.githubusercontent.com/40133739/230870134-9b516ccc-161b-4e69-a0ff-9e769408c09f.PNG)

**Comment by changwxx** [comment]
This seems very unreasonable. Please ensure your experimental setting is the same as our originally provided code.  If you did not change anything, maybe this is your print bug or something. We highly recommend you use the tensorboard monitoring training process, as it guarantees a bug-free version of our method.

We can achieve `cls_common_acc` around 0.46 and `cls_tp_acc around` 0.55 after 1k global steps training according to our experimental log.

**Comment by WangBowen7** [comment]
> This seems very unreasonable. Please ensure your experimental setting is the same as our originally provided code. If you did not change anything, maybe this is your print bug or something. We can achieve `cls_common_acc` around 0.46 and `cls_tp_acc around` 0.55 after 1k global steps training according to our experimental log. We highly recommend you use the tensorboard monitoring training process, as it guarantees a bug-free version of our method.

Thank you very much for your reply. I have resolved this issue and the reason for it is due to the version of POT, which I previously used 0.9.0.
