### ISSUE TITLE
Threading issues

### ISSUE THREAD

**Issue by WangQingchen123** [changwxx/UniOT-for-UniDA#4]
When I run main.py, I get the following error:
RuntimeError: 
        An attempt has been made to start a new process before the
        current process has finished its bootstrapping phase.

        This probably means that you are not using fork to start your
        child processes and you have forgotten to use the proper idiom
        in the main module:

            if __name__ == '__main__':
                freeze_support()
                ...

        The "freeze_support()" line can be omitted if the program
        is not going to be frozen to produce an executable.
    w.start()

**Comment by changwxx** [comment]
We did not manually initiate any threads or processes in our original code. And we did not encounter any such issues.
Have you followed the instructions in the readme file and tried executing the following command in your command line: `python main.py --gpu 0 --exp office31 --dataset office31 --source amazon --target dslr`?
